version: 2.1

jobs:
  test_blog:
    working_directory: ~/blog-project
    docker:
      - image: cimg/python:3.11.2
        environment:
          PGHOST: 127.0.0.1
          PGUSER: DB_USER

      - image: cimg/postgres:15.4
        environment:
          POSTGRES_USER: DB_USER
          POSTGRES_PASSWORD: password4
          POSTGRES_DB: blog_api_db
    steps:
      - checkout
      - run:
          name: "Check Python Version"
          command: python --version
      - run:
          name: "Check env"
          command: env


workflows:
  commit:
    jobs:
      - test_blog