version: 2.1

jobs:
  test_blog:
    docker:
        - image: cimg/python:3.11.2
        - image: cimg/postgres:15.4.0
    steps:
      - checkout
      - run:
          name: "Check Python Version"
          command: python --version