version: 2.1

jobs:
  test_blog:
    working_directory: ~/blog-project
    docker:
      - image: cimg/python:3.11.2
        environment:
          PGHOST: localhost
          PGUSER: DB_USER

      - image: cimg/postgres:15.4
        environment:
          POSTGRES_USER: DB_USER
          POSTGRES_PASSWORD: DB_PASS
          POSTGRES_DB: blog_api_db
    steps:
      - checkout
      - run:
          name: "Wait for db setup"
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: "Check Python Version"
          command: python --version
      - run:
          name: "Upgrade pip"
          command: python -m pip install --upgrade pip
      - run:
          name: "Install Requirements"
          command: pip install -r requirements.txt
      - run:
          name: "Run Tests"
          command: pytest -v


workflows:
  commit:
    jobs:
      - test_blog