"""update post_like table

Revision ID: a44b97876447
Revises: 98ee045e543a
Create Date: 2023-09-05 17:37:43.620511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44b97876447'
down_revision: Union[str, None] = '98ee045e543a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_likes', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint('comment_likes_account_id_fkey', 'comment_likes', type_='foreignkey')
    op.create_foreign_key(None, 'comment_likes', 'accounts', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment_likes', 'account_id')
    op.add_column('post_likes', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint('post_likes_account_id_fkey', 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'accounts', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_likes', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_likes', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key('post_likes_account_id_fkey', 'post_likes', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_likes', 'author_id')
    op.add_column('comment_likes', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.create_foreign_key('comment_likes_account_id_fkey', 'comment_likes', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment_likes', 'author_id')
    # ### end Alembic commands ###
